[build]
  command = "CI='' react-scripts build"  
  functions = "netlify/functions"    
  publish = "/build"    
  NODE_VERSION = "14.15.4"     
  NPM_VERSION = "7.20.2"`
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200